UserBundle_login:
    path:  /login
    defaults: { _controller: UserBundle:Login:login }

AssociationBundle_homepage:
    path:  /
    defaults: { _controller: AssociationBundle:Default:index }

AssociationBundle_association:
    path:  /association
    defaults: { _controller: AssociationBundle:Association:association }

AssociationBundle_update:
    path:  /update
    defaults: { _controller: AssociationBundle:Association:update }

DemandesubventionBundle_demande:
    path: /demande
    defaults: { _controller: DemandeSubventionBundle:Demande:dossier }
